name: 'Glimpse'
description: 'Upload files to a specific branch and return file URLs'
author: 'Blueswen'
inputs:
  directory:
    description: 'Directory containing files to upload'
    required: true
    default: '.'
  branch:
    description: 'Target branch to upload files to'
    required: false
    default: 'glimpse'
  generations:
    description: 'Number of generations to keep'
    required: false
    default: '5'
  token:
    description: 'GitHub token for authentication'
    required: true
outputs:
  file_urls:
    description: 'Comma-separated list of uploaded file URLs'
runs:
  using: 'docker'
  image: 'ghcr.io/blueswen/glimpse-action:v1.0.0'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.branch }}
    - ${{ inputs.generations }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
