name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # for git tagging if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release (draft)
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update v1 tag to point to this release
        run: |
          git fetch --tags
          git tag -f v1 ${{ github.ref_name }}
          git push -f origin v1
