name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # for git tagging if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release (draft)
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update floating major tag
        run: |
          MAJOR_TAG=$(echo "${{ github.ref_name }}" | grep -oE '^v[0-9]+')
          echo "Tagging current commit with $MAJOR_TAG"
          git tag -f "$MAJOR_TAG"
          git push origin "refs/tags/$MAJOR_TAG" --force
