name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # for git tagging if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release (draft)
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update floating major tag
        run: |
          git fetch --tags
          VERSION="${{ github.ref_name }}"  # → v1.2.3
          MAJOR_TAG=$(echo "$VERSION" | grep -oE '^v[0-9]+')
          echo "Updating floating tag: $MAJOR_TAG → $VERSION"
          
          # Check if the tag already exists and points to the correct commit
          if git rev-parse "$MAJOR_TAG" >/dev/null 2>&1; then
            CURRENT_COMMIT=$(git rev-parse "$MAJOR_TAG")
            NEW_COMMIT=$(git rev-parse "$VERSION")
            if [ "$CURRENT_COMMIT" = "$NEW_COMMIT" ]; then
              echo "Tag $MAJOR_TAG already points to $VERSION. Skipping update."
              exit 0
            fi
          fi
          
          git tag -f "$MAJOR_TAG" "$VERSION"
          git push origin "$MAJOR_TAG" --force
